apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
  name: agones-allocator-hpa
  namespace: ${namespace}
spec:
  maxReplicas: 20
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: agones-allocator
  targetCPUUtilizationPercentage: 60
---
